version: 2.1
orbs:
  python: circleci/python@2.0.3

jobs:
  resetall: # this can be any name you choose
    machine: # executor type
      image: ubuntu-2004:current
    steps:
      - checkout 
      #- python/install-packages:
          #pkg-manager: pip
      - run:
          name: Run tests
          command: sudo apt update && sudo apt-get install python3.8 && sudo pip install setuptools --upgrade && sudo pip install -r requirements.txt  && python3 resetk.py

workflows:
  reset_st:
    jobs:
      - resetall

