version: 2.1
orbs:
  python: circleci/python@2.0.3

jobs:
  resetall: # this can be any name you choose
    machine: # executor type
      image: ubuntu-2004:current
    steps:
      - checkout
      - update_all_soft:
        name: softs
        run: sudo apt update && sudo apt upgrade 
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python3 resetk.py

workflows:
  reset_st:
    jobs:
      - resetall

