version: 2.1
orbs:
  python: circleci/python@2.0.3

jobs:
  resetall: # this can be any name you choose
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python resetk.py

workflows:
  test_my_app:
    jobs:
      - resetall

