version: 2.1



jobs:
  resetall: # this can be any name you choose
    machine: # executor type
      image: ubuntu-2004:current
    steps:
      - checkout 
      #- python/install-packages:
          #pkg-manager: pip
      - run:
          name: Run tests
          command: sudo apt-get install chromium-browser && sudo  python3 resetk.py

workflows:
  triggers:
    - schedule:
        cron: "0 0-23 * * *"
  reset_st:
    jobs:
      - resetall

